// Catecismo Breve de Westminster (1647) — Domínio público
// Tradução: padrão evangélico reformado em pt-BR (Editora Os Puritanos / Cultura Cristã)
// 107 perguntas e respostas

export interface CatecismoBrevePergunta {
  numero: number
  pergunta: string
  resposta: string
  versiculos: string[] // referências bíblicas de prova
}

export const CATECISMO_BREVE: CatecismoBrevePergunta[] = [
  {
    numero: 1,
    pergunta: 'Qual é o fim principal do homem?',
    resposta: 'O fim principal do homem é glorificar a Deus e gozar d\'Ele para sempre.',
    versiculos: ['1Co 10.31', 'Sl 73.25-28'],
  },
  {
    numero: 2,
    pergunta: 'Que regra deu Deus para nos dirigir em como podemos glorificá-lo e gozar d\'Ele?',
    resposta: 'A Palavra de Deus, contida nas Escrituras do Antigo e do Novo Testamento, é a única regra que nos dirige em como podemos glorificá-lo e gozar d\'Ele.',
    versiculos: ['2Tm 3.16', 'Ef 2.20'],
  },
  {
    numero: 3,
    pergunta: 'O que principalmente ensinam as Escrituras?',
    resposta: 'As Escrituras ensinam principalmente o que o homem deve crer acerca de Deus, e que dever Deus requer do homem.',
    versiculos: ['2Tm 1.13', 'Mq 6.8'],
  },
  {
    numero: 4,
    pergunta: 'O que é Deus?',
    resposta: 'Deus é um Espírito, infinito, eterno e imutável em seu ser, sabedoria, poder, santidade, justiça, bondade e verdade.',
    versiculos: ['Jo 4.24', 'Sl 147.5', 'Sl 90.2', 'Tg 1.17', 'Ap 4.8'],
  },
  {
    numero: 5,
    pergunta: 'Há mais de um Deus?',
    resposta: 'Há somente um Deus, vivo e verdadeiro.',
    versiculos: ['Dt 6.4', 'Jr 10.10'],
  },
  {
    numero: 6,
    pergunta: 'Quantas pessoas há na Divindade?',
    resposta: 'Na Divindade há três pessoas: o Pai, o Filho, e o Espírito Santo; e estas três são um só Deus, da mesma substância, iguais em poder e glória.',
    versiculos: ['1Jo 5.7', 'Mt 28.19'],
  },
  {
    numero: 7,
    pergunta: 'O que são os decretos de Deus?',
    resposta: 'Os decretos de Deus são o seu propósito eterno, conforme o conselho da sua vontade, pelo qual, para sua própria glória, predestinou tudo o que há de acontecer.',
    versiculos: ['Ef 1.11', 'Rm 11.36'],
  },
  {
    numero: 8,
    pergunta: 'Como executa Deus os seus decretos?',
    resposta: 'Deus executa os seus decretos nas obras de criação e providência.',
    versiculos: ['Ap 4.11', 'Dn 4.35'],
  },
  {
    numero: 9,
    pergunta: 'O que é a obra da criação?',
    resposta: 'A obra da criação é fazer Deus tudo do nada, pelo poder de sua palavra, em seis dias, e tudo muito bom.',
    versiculos: ['Gn 1.1', 'Hb 11.3'],
  },
  {
    numero: 10,
    pergunta: 'Como criou Deus o homem?',
    resposta: 'Deus criou o homem, macho e fêmea, à sua própria imagem, em conhecimento, justiça e santidade, com domínio sobre as criaturas.',
    versiculos: ['Gn 1.27', 'Cl 3.10', 'Ef 4.24'],
  },
  {
    numero: 11,
    pergunta: 'O que são as obras de providência de Deus?',
    resposta: 'As obras de providência de Deus são as suas obras santíssimas, sapientíssimas e poderosíssimas de preservar e governar todas as suas criaturas e todos os atos delas.',
    versiculos: ['Sl 145.17', 'Hb 1.3'],
  },
  {
    numero: 12,
    pergunta: 'Em que ato especial de providência tratou Deus o homem, no estado em que foi criado?',
    resposta: 'Quando criou o homem, Deus firmou com ele um pacto de vida, com a condição de obediência perfeita, proibindo-lhe comer da árvore do conhecimento do bem e do mal, sob pena de morte.',
    versiculos: ['Gl 3.12', 'Gn 2.17'],
  },
  {
    numero: 13,
    pergunta: 'Permaneceu o nosso primeiro pai no estado em que foi criado?',
    resposta: 'Nosso primeiro pai, tendo liberdade de vontade, caiu de seu estado original, pecando contra Deus.',
    versiculos: ['Ec 7.29', 'Gn 3.6-8'],
  },
  {
    numero: 14,
    pergunta: 'O que é o pecado?',
    resposta: 'O pecado é qualquer falta de conformidade à lei de Deus, ou transgressão da mesma.',
    versiculos: ['1Jo 3.4'],
  },
  {
    numero: 15,
    pergunta: 'Em que consistiu o pecado com que nosso primeiro pai caiu?',
    resposta: 'O pecado com que nosso primeiro pai caiu consistiu em comer o fruto proibido.',
    versiculos: ['Gn 3.6', 'Ec 7.29'],
  },
  {
    numero: 16,
    pergunta: 'Caiu toda a humanidade na primeira transgressão de Adão?',
    resposta: 'Tendo Adão feito o pacto não somente por si mesmo, mas também por toda a sua posteridade, toda a humanidade, descendo dele por geração ordinária, pecou nele e caiu com ele na sua primeira transgressão.',
    versiculos: ['Rm 5.12', '1Co 15.22'],
  },
  {
    numero: 17,
    pergunta: 'A que estado reduziu a queda o homem?',
    resposta: 'A queda reduziu o homem ao estado de pecado e miséria.',
    versiculos: ['Rm 5.18-19'],
  },
  {
    numero: 18,
    pergunta: 'Em que consiste a pecaminosidade daquele estado em que o homem caiu?',
    resposta: 'A pecaminosidade do estado em que o homem caiu consiste: no pecado original, que inclui a culpa do primeiro pecado de Adão, a falta da justiça original, e a corrupção de toda a sua natureza; e em todos os pecados atuais que procedem dela.',
    versiculos: ['Rm 5.12', 'Rm 3.10-19', 'Tg 1.14-15'],
  },
  {
    numero: 19,
    pergunta: 'Qual é a miséria daquele estado em que o homem caiu?',
    resposta: 'Toda a humanidade, pela sua queda, perdeu a comunhão com Deus, ficou sob a sua ira e maldição, tornando-se assim sujeita a todas as misérias desta vida, à morte mesma, e às penas do inferno para sempre.',
    versiculos: ['Ef 2.1-3', 'Gl 3.10', 'Rm 6.23'],
  },
  {
    numero: 20,
    pergunta: 'Deixou Deus toda a humanidade perecer no estado de pecado e miséria?',
    resposta: 'Não; pois, desde a eternidade, Deus elegeu alguns para terem vida eterna, firmando com eles um pacto de graça, para os livrar do estado de pecado e miséria, e introduzi-los no estado de salvação, pelo Redentor.',
    versiculos: ['Ef 1.4', 'Rm 3.20-22'],
  },
  {
    numero: 21,
    pergunta: 'Quem é o Redentor dos eleitos de Deus?',
    resposta: 'O único Redentor dos eleitos de Deus é o Senhor Jesus Cristo, que, sendo o eterno Filho de Deus, fez-se homem, e assim foi, e continua a ser, Deus e homem em duas naturezas distintas, numa só pessoa, para sempre.',
    versiculos: ['1Tm 2.5', 'Jo 1.14', 'Cl 2.9'],
  },
  {
    numero: 22,
    pergunta: 'Como Cristo, sendo o Filho de Deus, se fez homem?',
    resposta: 'Cristo, o Filho de Deus, fez-se homem tomando para si um corpo real e uma alma racional, sendo concebido pelo poder do Espírito Santo, no ventre da Virgem Maria, e dela nascendo, mas sem pecado.',
    versiculos: ['Jo 1.14', 'Lc 1.31-35', 'Hb 4.15'],
  },
  {
    numero: 23,
    pergunta: 'Que ofícios exerce Cristo como nosso Redentor?',
    resposta: 'Cristo como nosso Redentor exerce os ofícios de profeta, sacerdote e rei, tanto no seu estado de humilhação como de exaltação.',
    versiculos: ['At 3.21-22', 'Hb 12.25', 'Hb 5.5-6', 'Sl 2.6'],
  },
  {
    numero: 24,
    pergunta: 'Como exerce Cristo o ofício de profeta?',
    resposta: 'Cristo exerce o ofício de profeta revelando-nos, pela sua Palavra e Espírito, a vontade de Deus para a nossa salvação.',
    versiculos: ['Jo 15.15', 'Jo 20.31'],
  },
  {
    numero: 25,
    pergunta: 'Como exerce Cristo o ofício de sacerdote?',
    resposta: 'Cristo exerce o ofício de sacerdote oferecendo-se a si mesmo uma vez como sacrifício para satisfazer a justiça divina e nos reconciliar com Deus, e intercedendo continuamente por nós.',
    versiculos: ['Hb 9.14', 'Hb 2.17', 'Hb 7.24-25'],
  },
  {
    numero: 26,
    pergunta: 'Como exerce Cristo o ofício de rei?',
    resposta: 'Cristo exerce o ofício de rei sujeitando-nos a si mesmo, governando-nos e defendendo-nos, e refreando e vencendo todos os seus e nossos inimigos.',
    versiculos: ['At 15.14-17', 'Is 33.22', 'Sl 110.1-2'],
  },
  {
    numero: 27,
    pergunta: 'Em que consistiu a humilhação de Cristo?',
    resposta: 'A humilhação de Cristo consistiu em nascer, e isso em baixa condição, ser posto sob a lei, sofrer as misérias desta vida, a ira de Deus e a morte maldita da cruz; ser sepultado, e ficar sob o poder da morte por algum tempo.',
    versiculos: ['Lc 2.7', 'Gl 4.4', 'Is 53.3', 'Lc 22.44', 'Mt 27.46', 'Fp 2.8'],
  },
  {
    numero: 28,
    pergunta: 'Em que consiste a exaltação de Cristo?',
    resposta: 'A exaltação de Cristo consiste na sua ressurreição dentre os mortos ao terceiro dia, na sua ascensão ao céu, em estar à destra de Deus Pai, e em vir para julgar o mundo no último dia.',
    versiculos: ['1Co 15.4', 'Mc 16.19', 'At 1.11', 'At 17.31'],
  },
  {
    numero: 29,
    pergunta: 'Como nos tornamos participantes da redenção que Cristo adquiriu?',
    resposta: 'Tornamo-nos participantes da redenção que Cristo adquiriu pela aplicação eficaz dela a nós pelo seu Espírito Santo.',
    versiculos: ['Jo 1.11-12', 'Jo 3.5-6'],
  },
  {
    numero: 30,
    pergunta: 'Como o Espírito Santo aplica a nós a redenção que Cristo adquiriu?',
    resposta: 'O Espírito Santo aplica a nós a redenção que Cristo adquiriu, operando a fé em nós, e unindo-nos assim a Cristo pela nossa eficaz vocação.',
    versiculos: ['Ef 1.13-14', 'Jo 6.37', 'Ef 2.8'],
  },
  {
    numero: 31,
    pergunta: 'O que é a eficaz vocação?',
    resposta: 'A eficaz vocação é a obra do Espírito de Deus, pela qual, convencendo-nos do nosso pecado e miséria, iluminando o nosso entendimento no conhecimento de Cristo, e renovando a nossa vontade, nos persuade e nos habilita a abraçar Jesus Cristo, tal como é livremente oferecido no evangelho.',
    versiculos: ['2Tm 1.9', 'At 26.18', 'Ez 36.26-27', 'Jo 6.44-45'],
  },
  {
    numero: 32,
    pergunta: 'Que benefícios têm nesta vida os que são eficazmente chamados?',
    resposta: 'Os que são eficazmente chamados participam nesta vida da justificação, da adoção e da santificação, e dos vários outros benefícios que nesta vida acompanham ou procedem destes.',
    versiculos: ['Rm 8.30', 'Ef 1.5', '1Co 1.30'],
  },
  {
    numero: 33,
    pergunta: 'O que é a justificação?',
    resposta: 'A justificação é um ato de livre graça de Deus pelo qual ele perdoa todos os nossos pecados, e nos aceita como justos perante ele, somente imputando-nos a justiça de Cristo, e recebendo-a somente pela fé.',
    versiculos: ['Rm 3.24-25', 'Rm 4.6-8', 'Fp 3.9'],
  },
  {
    numero: 34,
    pergunta: 'O que é a adoção?',
    resposta: 'A adoção é um ato de livre graça de Deus pelo qual somos recebidos no número, e temos direito a todos os privilégios dos filhos de Deus.',
    versiculos: ['1Jo 3.1', 'Jo 1.12'],
  },
  {
    numero: 35,
    pergunta: 'O que é a santificação?',
    resposta: 'A santificação é a obra da graça livre de Deus, pela qual somos renovados em toda a nossa pessoa segundo a imagem de Deus, e somos habilitados, cada vez mais, a morrer para o pecado e viver para a justiça.',
    versiculos: ['2Ts 2.13', 'Rm 6.4-6', 'Rm 8.1'],
  },
  {
    numero: 36,
    pergunta: 'Que benefícios acompanham ou procedem nesta vida da justificação, adoção e santificação?',
    resposta: 'Os benefícios que nesta vida acompanham ou procedem da justificação, adoção e santificação são: segurança do amor de Deus, paz de consciência, alegria no Espírito Santo, aumento da graça e perseverança nela até ao fim.',
    versiculos: ['Rm 5.1-2', 'Rm 5.5', 'Rm 14.17', 'Pv 4.18', '1Jo 5.13'],
  },
  {
    numero: 37,
    pergunta: 'Que benefícios recebem os crentes de Cristo na morte?',
    resposta: 'Na morte, as almas dos crentes são aperfeiçoadas em santidade, e logo passam a gozar de glória; e os seus corpos, estando ainda unidos a Cristo, repousam nos seus túmulos até à ressurreição.',
    versiculos: ['Hb 12.23', 'Fp 1.23', '1Ts 4.14'],
  },
  {
    numero: 38,
    pergunta: 'Que benefícios receberão os crentes de Cristo na ressurreição?',
    resposta: 'Na ressurreição, os crentes, sendo levantados em glória, serão publicamente reconhecidos e absolvidos no dia do julgamento, e feitos perfeitamente bem-aventurados no pleno gozo de Deus para todo o sempre.',
    versiculos: ['1Co 15.43', 'Mt 25.33-34', '1Jo 3.2', '1Ts 4.17'],
  },
  {
    numero: 39,
    pergunta: 'Que dever requer Deus do homem?',
    resposta: 'O dever que Deus requer do homem é a obediência à sua vontade revelada.',
    versiculos: ['Mq 6.8', 'Rm 12.1-2'],
  },
  {
    numero: 40,
    pergunta: 'Que regra revelou Deus ao homem primeiro para a obediência?',
    resposta: 'A regra que Deus revelou primeiro ao homem para a obediência foi a lei moral.',
    versiculos: ['Rm 2.14-15', 'Rm 10.5'],
  },
  {
    numero: 41,
    pergunta: 'Onde está resumida a lei moral?',
    resposta: 'A lei moral está resumida nos dez mandamentos.',
    versiculos: ['Dt 10.4', 'Mt 19.17'],
  },
  {
    numero: 42,
    pergunta: 'Qual é a suma dos dez mandamentos?',
    resposta: 'A suma dos dez mandamentos é amar ao Senhor nosso Deus com todo o coração, com toda a alma, com todas as forças e com todo o entendimento, e ao nosso próximo como a nós mesmos.',
    versiculos: ['Mt 22.37-40'],
  },
  {
    numero: 43,
    pergunta: 'Qual é o preâmbulo dos dez mandamentos?',
    resposta: 'O preâmbulo dos dez mandamentos é: "Eu sou o Senhor teu Deus, que te tirei da terra do Egito, da casa da servidão."',
    versiculos: ['Ex 20.2', 'Dt 5.6'],
  },
  {
    numero: 44,
    pergunta: 'Que nos ensina o preâmbulo dos dez mandamentos?',
    resposta: 'O preâmbulo dos dez mandamentos nos ensina que, sendo ele o Senhor nosso Deus e Redentor, temos obrigação de guardar todos os seus mandamentos.',
    versiculos: ['Lc 1.74-75', '1Pe 1.15-19'],
  },
  {
    numero: 45,
    pergunta: 'Qual é o primeiro mandamento?',
    resposta: '"Não terás outros deuses diante de mim."',
    versiculos: ['Ex 20.3', 'Dt 5.7'],
  },
  {
    numero: 46,
    pergunta: 'O que requer o primeiro mandamento?',
    resposta: 'O primeiro mandamento requer que conheçamos e reconheçamos a Deus para ser o único Deus verdadeiro e nosso Deus, e que o adoremos e glorifiquemos como corresponde.',
    versiculos: ['1Cr 28.9', 'Dt 26.17', 'Mt 4.10', 'Sl 29.2'],
  },
  {
    numero: 47,
    pergunta: 'O que proíbe o primeiro mandamento?',
    resposta: 'O primeiro mandamento proíbe a negação de Deus, ou o não lhe render a adoração e glória que lhe é devida; proíbe o ateísmo, a idolatria, e qualquer reconhecimento de qualquer outro como Deus.',
    versiculos: ['Sl 14.1', 'Rm 1.20-21', 'Dt 6.14'],
  },
  {
    numero: 48,
    pergunta: 'O que principalmente nos ensina a expressão "diante de mim" no primeiro mandamento?',
    resposta: 'A expressão "diante de mim" no primeiro mandamento nos ensina que Deus, que vê tudo, nota e se ofende muito com o pecado de ter outros deuses.',
    versiculos: ['Ez 8.5-6', 'Sl 44.20-21'],
  },
  {
    numero: 49,
    pergunta: 'Qual é o segundo mandamento?',
    resposta: '"Não farás para ti imagem esculpida, nem figura alguma do que há em cima no céu, nem embaixo na terra, nem no mar abaixo da terra. Não te inclinarás a elas nem as servirás; porque eu, o Senhor teu Deus, sou um Deus zeloso, visitando a iniquidade dos pais nos filhos até à terceira e quarta geração dos que me odeiam, e usando de misericórdia com milhares dos que me amam e guardam os meus mandamentos."',
    versiculos: ['Ex 20.4-6', 'Dt 5.8-10'],
  },
  {
    numero: 50,
    pergunta: 'O que requer o segundo mandamento?',
    resposta: 'O segundo mandamento requer que recebamos, observemos e guardemos puros e inteiros todos os ordenamentos religiosos que Deus nos prescreveu em sua Palavra.',
    versiculos: ['Dt 32.46', 'Mt 28.20', 'At 2.42'],
  },
  {
    numero: 51,
    pergunta: 'O que proíbe o segundo mandamento?',
    resposta: 'O segundo mandamento proíbe a adoração de Deus por imagens, ou por qualquer outro modo não prescrito na sua Palavra.',
    versiculos: ['Dt 4.15-19', 'Ex 32.5-8'],
  },
  {
    numero: 52,
    pergunta: 'Que razões estão ligadas ao segundo mandamento?',
    resposta: 'As razões ligadas ao segundo mandamento são o soberano domínio de Deus sobre nós, o direito de propriedade que tem sobre nós, e o fervor de sua adoração para conosco, que não tolera que nos desviemos.',
    versiculos: ['Sl 45.11', 'Ex 34.13-14'],
  },
  {
    numero: 53,
    pergunta: 'Qual é o terceiro mandamento?',
    resposta: '"Não tomarás o nome do Senhor teu Deus em vão; porque o Senhor não terá por inocente aquele que tomar o seu nome em vão."',
    versiculos: ['Ex 20.7', 'Dt 5.11'],
  },
  {
    numero: 54,
    pergunta: 'O que requer o terceiro mandamento?',
    resposta: 'O terceiro mandamento requer o uso reverente e santo do nome de Deus, dos seus títulos, atributos, ordenamentos, Palavra e obras.',
    versiculos: ['Mt 6.9', 'Dt 28.58', 'Sl 138.1-2', 'Ap 15.3-4'],
  },
  {
    numero: 55,
    pergunta: 'O que proíbe o terceiro mandamento?',
    resposta: 'O terceiro mandamento proíbe toda o profanação ou abuso do nome de Deus.',
    versiculos: ['Ml 2.2', 'Ml 1.6-7', 'At 5.4'],
  },
  {
    numero: 56,
    pergunta: 'Que razão está ligada ao terceiro mandamento?',
    resposta: 'A razão ligada ao terceiro mandamento é que, ainda que os transgredentes escapem ao castigo dos homens, o Senhor nosso Deus não os terá por inocentes.',
    versiculos: ['1Sm 3.13', 'Dt 28.58-59'],
  },
  {
    numero: 57,
    pergunta: 'Qual é o quarto mandamento?',
    resposta: '"Lembra-te do sábado para o santificar. Seis dias trabalharás e farás toda a tua obra; mas o sétimo dia é o sábado do Senhor teu Deus. Não farás nenhuma obra, nem tu, nem teu filho, nem tua filha, nem o teu servo, nem a tua serva, nem o teu animal, nem o forasteiro que está dentro das tuas portas. Porque, em seis dias, o Senhor fez os céus e a terra, o mar e tudo o que neles há, e ao sétimo dia descansou; portanto o Senhor abençoou o sábado e o santificou."',
    versiculos: ['Ex 20.8-11', 'Dt 5.12-15'],
  },
  {
    numero: 58,
    pergunta: 'O que requer o quarto mandamento?',
    resposta: 'O quarto mandamento requer a observância de determinados tempos fixados por Deus para ser santos para ele, especialmente de um dia em sete, para ser um sábado santo para ele.',
    versiculos: ['Lv 19.3-4,30', 'Dt 5.12-14'],
  },
  {
    numero: 59,
    pergunta: 'De que dia da semana é o sábado agora observado sob o Novo Testamento?',
    resposta: 'Desde a ressurreição de Cristo, o sábado cristão é o primeiro dia da semana, e é chamado o Dia do Senhor.',
    versiculos: ['At 20.7', '1Co 16.1-2', 'Ap 1.10'],
  },
  {
    numero: 60,
    pergunta: 'Como se deve santificar o Dia do Senhor?',
    resposta: 'O Dia do Senhor deve ser santificado com um santo descanso todo o dia, de todas as obras e recreações mundanas; e com dedicar todo o tempo ao exercício do culto público e particular de Deus, salvo o exigido pelas obras de necessidade e misericórdia.',
    versiculos: ['Is 58.13-14', 'Lc 4.16', 'At 20.7', 'Mt 12.1-13'],
  },
  {
    numero: 61,
    pergunta: 'O que proíbe o quarto mandamento?',
    resposta: 'O quarto mandamento proíbe a omissão ou o descuido negligente das obrigações requeridas, e o profanar o dia por preguiça, ou fazer o que em si é pecado, ou por desnecessárias obras, palavras ou pensamentos mundanos.',
    versiculos: ['Ez 22.26', 'Am 8.5', 'Ez 23.38', 'Jr 17.27'],
  },
  {
    numero: 62,
    pergunta: 'Que razões estão ligadas ao quarto mandamento?',
    resposta: 'As razões ligadas ao quarto mandamento são as providências de Deus em nos dar seis dias da semana para os empregos do mundo, reservando para si a propriedade do sétimo; o seu exemplo: o Senhor descansou no sétimo dia; e a sua bênção ao dia do sábado.',
    versiculos: ['Ex 31.15-17', 'Gn 2.2-3'],
  },
  {
    numero: 63,
    pergunta: 'Qual é o quinto mandamento?',
    resposta: '"Honra teu pai e tua mãe, para que se prolonguem os teus dias na terra que o Senhor teu Deus te dá."',
    versiculos: ['Ex 20.12', 'Dt 5.16'],
  },
  {
    numero: 64,
    pergunta: 'O que requer o quinto mandamento?',
    resposta: 'O quinto mandamento requer que prestemos toda a honra e amor devidos àqueles que estão em posição superior, inferior ou igual à nossa.',
    versiculos: ['Rm 13.1', 'Ef 5.21-22', 'Ef 6.1,5'],
  },
  {
    numero: 65,
    pergunta: 'O que proíbe o quinto mandamento?',
    resposta: 'O quinto mandamento proíbe a negligência dos deveres, ou qualquer coisa que desonre ou prejudique aqueles que estão em posição superior, inferior ou igual à nossa.',
    versiculos: ['Rm 13.8', 'Pv 30.11,17'],
  },
  {
    numero: 66,
    pergunta: 'Que razão está ligada ao quinto mandamento?',
    resposta: 'A razão ligada ao quinto mandamento é a promessa de longa vida e prosperidade (tanto quanto redunde para a glória de Deus e bem dos mesmos) para todos os que guardem este mandamento.',
    versiculos: ['Ef 6.2-3'],
  },
  {
    numero: 67,
    pergunta: 'Qual é o sexto mandamento?',
    resposta: '"Não matarás."',
    versiculos: ['Ex 20.13', 'Dt 5.17'],
  },
  {
    numero: 68,
    pergunta: 'O que requer o sexto mandamento?',
    resposta: 'O sexto mandamento requer todos os esforços lícitos para preservar a nossa própria vida e a do próximo.',
    versiculos: ['Ef 5.28-29', 'Sl 82.3-4', 'Pv 24.11-12', 'At 16.28'],
  },
  {
    numero: 69,
    pergunta: 'O que proíbe o sexto mandamento?',
    resposta: 'O sexto mandamento proíbe tirar injustamente a nossa própria vida ou a do próximo, e tudo o que tende a isso.',
    versiculos: ['At 16.28', 'Gn 9.6', 'Mt 5.21-22'],
  },
  {
    numero: 70,
    pergunta: 'Qual é o sétimo mandamento?',
    resposta: '"Não adulterarás."',
    versiculos: ['Ex 20.14', 'Dt 5.18'],
  },
  {
    numero: 71,
    pergunta: 'O que requer o sétimo mandamento?',
    resposta: 'O sétimo mandamento requer a preservação da nossa própria castidade e a do próximo, em corações, palavras e atos.',
    versiculos: ['1Co 7.2-3', '1Ts 4.4-5', 'Cl 4.6'],
  },
  {
    numero: 72,
    pergunta: 'O que proíbe o sétimo mandamento?',
    resposta: 'O sétimo mandamento proíbe todos os pensamentos, palavras e ações impuras.',
    versiculos: ['Mt 15.19', 'Ef 5.3-4'],
  },
  {
    numero: 73,
    pergunta: 'Qual é o oitavo mandamento?',
    resposta: '"Não furtarás."',
    versiculos: ['Ex 20.15', 'Dt 5.19'],
  },
  {
    numero: 74,
    pergunta: 'O que requer o oitavo mandamento?',
    resposta: 'O oitavo mandamento requer que legitimamente adquiramos e aumentemos os bens e o bom nome nosso e do próximo.',
    versiculos: ['Gn 30.30', 'Ef 4.28', 'Rm 12.17'],
  },
  {
    numero: 75,
    pergunta: 'O que proíbe o oitavo mandamento?',
    resposta: 'O oitavo mandamento proíbe tudo o que injustamente nos impede, ou impede ao próximo, de ter e aumentar bens e bom nome.',
    versiculos: ['1Tm 5.8', 'Pv 21.6', 'Ef 4.28'],
  },
  {
    numero: 76,
    pergunta: 'Qual é o nono mandamento?',
    resposta: '"Não dirás falso testemunho contra o teu próximo."',
    versiculos: ['Ex 20.16', 'Dt 5.20'],
  },
  {
    numero: 77,
    pergunta: 'O que requer o nono mandamento?',
    resposta: 'O nono mandamento requer que preservemos a verdade entre os homens e a boa reputação do nosso próximo e a nossa própria, e que digamos a verdade e a façamos prevalecer.',
    versiculos: ['Zc 8.16', 'Ef 4.25', '3Jo 12'],
  },
  {
    numero: 78,
    pergunta: 'O que proíbe o nono mandamento?',
    resposta: 'O nono mandamento proíbe tudo o que é prejudicial à verdade ou ao bom nome do nosso próximo.',
    versiculos: ['Pv 19.5', 'Sl 15.2-3'],
  },
  {
    numero: 79,
    pergunta: 'Qual é o décimo mandamento?',
    resposta: '"Não cobiçarás a casa do teu próximo; não cobiçarás a mulher do teu próximo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu asno, nem coisa alguma do teu próximo."',
    versiculos: ['Ex 20.17', 'Dt 5.21'],
  },
  {
    numero: 80,
    pergunta: 'O que requer o décimo mandamento?',
    resposta: 'O décimo mandamento requer que nos contentemos com a nossa condição e que tenhamos uma disposição caridosa e amorosa para com o próximo e o que é dele.',
    versiculos: ['Hb 13.5', '1Tm 6.6', 'Jó 31.29', 'Rm 12.15'],
  },
  {
    numero: 81,
    pergunta: 'O que proíbe o décimo mandamento?',
    resposta: 'O décimo mandamento proíbe toda inveja, descontentamento com o que temos e todo desejo pecaminoso do que é do próximo.',
    versiculos: ['Gl 5.26', 'Tg 3.14-16', '1Co 10.10', 'Rm 7.7-8'],
  },
  {
    numero: 82,
    pergunta: 'Pode alguém guardar perfeitamente os mandamentos de Deus?',
    resposta: 'Nenhum homem, desde a queda, é capaz nesta vida de guardar perfeitamente os mandamentos de Deus; mas os transgride em pensamentos, palavras e atos diariamente.',
    versiculos: ['Ec 7.20', 'Gn 8.21', 'Rm 3.9-19', 'Tg 3.2-13'],
  },
  {
    numero: 83,
    pergunta: 'São todos os pecados igualmente atrozes?',
    resposta: 'Alguns pecados em si mesmos, e por causa de várias agravantes, são mais atrozes perante Deus do que outros.',
    versiculos: ['Ez 8.13', 'Jo 19.11', '1Jo 5.16'],
  },
  {
    numero: 84,
    pergunta: 'O que merece todo pecado?',
    resposta: 'Todo pecado merece a ira e a maldição de Deus, tanto nesta vida como na que há de vir.',
    versiculos: ['Ef 5.6', 'Gl 3.10', 'Lm 3.39', 'Mt 25.41'],
  },
  {
    numero: 85,
    pergunta: 'Que requer Deus de nós para escaparmos da sua ira e maldição, que merecemos por causa do pecado?',
    resposta: 'Para escaparmos da ira e maldição de Deus que merecemos por causa do pecado, Deus requer de nós fé em Jesus Cristo, arrependimento para a vida, e o uso diligente de todos os meios externos pelos quais Cristo nos comunica os benefícios da redenção.',
    versiculos: ['At 20.21', 'Mt 3.7-8', 'Pv 2.1-5', 'Pv 8.33-36'],
  },
  {
    numero: 86,
    pergunta: 'O que é a fé em Jesus Cristo?',
    resposta: 'A fé em Jesus Cristo é uma graça salvadora, pela qual recebemos e descansamos sobre Cristo somente para a salvação, tal como nos é oferecido no Evangelho.',
    versiculos: ['Hb 10.39', 'Jo 1.12', 'Fp 3.9'],
  },
  {
    numero: 87,
    pergunta: 'O que é o arrependimento para a vida?',
    resposta: 'O arrependimento para a vida é uma graça salvadora pela qual um pecador, tendo verdadeiro senso dos seus pecados e apreendendo a misericórdia de Deus em Cristo, com dor e ódio dos seus pecados, se volta deles para Deus, com propósito e esforço de uma nova obediência.',
    versiculos: ['At 11.18', 'Ez 36.31', '2Co 7.11', 'Sl 119.59'],
  },
  {
    numero: 88,
    pergunta: 'Quais são os meios externos e ordinários pelos quais Cristo nos comunica os benefícios da redenção?',
    resposta: 'Os meios externos e ordinários pelos quais Cristo nos comunica os benefícios da redenção são as suas ordenanças, especialmente a Palavra, os sacramentos e a oração; todos os quais são feitos eficazes para os eleitos para a salvação.',
    versiculos: ['Mt 28.19-20', 'At 2.42,46-47'],
  },
  {
    numero: 89,
    pergunta: 'Como a Palavra se torna eficaz para a salvação?',
    resposta: 'O Espírito de Deus faz da leitura, mas especialmente da pregação da Palavra, um meio eficaz de convencer e converter os pecadores, e de os edificar em santidade e conforto, pela fé para a salvação.',
    versiculos: ['Ne 8.8', 'At 26.18', '1Ts 1.6', 'Rm 1.16'],
  },
  {
    numero: 90,
    pergunta: 'Como deve ser lida e ouvida a Palavra para se tornar eficaz para a salvação?',
    resposta: 'Para que a Palavra se torne eficaz para a salvação, devemos atender a ela com diligência, preparação e oração, recebê-la com fé e amor, alojá-la em nossos corações, e praticá-la em nossa vida.',
    versiculos: ['Pv 8.34', 'Lc 8.18', '1Pe 2.1-2', 'Hb 4.2', '2Ts 2.10', 'Sl 119.11', 'Tg 1.25'],
  },
  {
    numero: 91,
    pergunta: 'Como os sacramentos se tornam meios eficazes de salvação?',
    resposta: 'Os sacramentos se tornam meios eficazes de salvação, não em virtude de qualquer poder deles mesmos ou de quem os administra, mas somente pela bênção de Cristo e pela operação do seu Espírito naqueles que os recebem pela fé.',
    versiculos: ['1Pe 3.21', '1Co 3.6-7', '1Co 12.13'],
  },
  {
    numero: 92,
    pergunta: 'O que é um sacramento?',
    resposta: 'Um sacramento é uma ordenança santa, instituída por Cristo, em que, por sinais sensíveis, Cristo e os benefícios da nova aliança são representados, selados e aplicados aos crentes.',
    versiculos: ['Gn 17.11', 'Rm 4.11', 'Mt 26.27-28'],
  },
  {
    numero: 93,
    pergunta: 'Quais são os sacramentos do Novo Testamento?',
    resposta: 'Os sacramentos do Novo Testamento são o batismo e a santa Ceia do Senhor.',
    versiculos: ['Mt 28.19', 'Mt 26.26-28'],
  },
  {
    numero: 94,
    pergunta: 'O que é o batismo?',
    resposta: 'O batismo é um sacramento no qual o lavar com água em nome do Pai, do Filho e do Espírito Santo, significa e sela o nosso enxerto em Cristo, a nossa participação nos benefícios do pacto da graça e o nosso compromisso de sermos do Senhor.',
    versiculos: ['Rm 6.4', 'Gl 3.27', 'Mt 28.19'],
  },
  {
    numero: 95,
    pergunta: 'A quem deve ser administrado o batismo?',
    resposta: 'O batismo não deve ser administrado senão àqueles que estão fora da Igreja visível, até que professem a sua fé em Cristo e obediência a ele; mas aos filhos dos que são membros de uma ou outra das igrejas, o batismo deve ser administrado.',
    versiculos: ['At 2.38', 'Mc 16.16', 'Gn 17.10', 'At 2.38-39', 'At 16.32-33'],
  },
  {
    numero: 96,
    pergunta: 'O que é a santa Ceia do Senhor?',
    resposta: 'A santa Ceia do Senhor é um sacramento, no qual, pela distribuição e recebimento do pão e do vinho, conforme a instituição de Cristo, é anunciada a morte dele; e os que a recebem dignamente, não carnalmente, mas pela fé, participam do seu corpo e sangue com todos os benefícios dele, para o seu alimento espiritual e crescimento em graça.',
    versiculos: ['1Co 11.23-26', '1Co 10.16'],
  },
  {
    numero: 97,
    pergunta: 'O que requer-se para receber dignamente a santa Ceia do Senhor?',
    resposta: 'Requer-se dos que querem receber dignamente a santa Ceia do Senhor que eles se examinem a si mesmos quanto ao seu conhecimento, para discernir o corpo do Senhor; quanto à sua fé, para se alimentarem dele; quanto ao seu arrependimento, amor e nova obediência; para que não comam e bebam seu próprio julgamento.',
    versiculos: ['1Co 11.28-29', '2Co 13.5'],
  },
  {
    numero: 98,
    pergunta: 'O que é a oração?',
    resposta: 'A oração é a oferta das nossas almas a Deus, em nome de Cristo, com confissão dos nossos pecados e reconhecimento grato das suas misericórdias.',
    versiculos: ['Sl 62.8', 'Jo 16.23', 'Dn 9.4', 'Fp 4.6'],
  },
  {
    numero: 99,
    pergunta: 'Que regra deu Deus para nos dirigir na oração?',
    resposta: 'Toda a Palavra de Deus é útil para nos dirigir na oração; mas a regra especial é aquela forma de oração que Cristo ensinou a seus discípulos, chamada Pai Nosso.',
    versiculos: ['1Jo 5.14', 'Mt 6.9-13'],
  },
  {
    numero: 100,
    pergunta: 'O que nos ensina o prefácio do Pai Nosso?',
    resposta: 'O prefácio do Pai Nosso ("Pai nosso que estás no céu") nos ensina que nos devemos aproximar de Deus com santa reverência e confiança, como filhos de um Pai poderoso e bom; e que devemos orar com e por outros.',
    versiculos: ['Is 64.9', 'Lc 11.13', 'Rm 8.15', 'At 12.5'],
  },
  {
    numero: 101,
    pergunta: 'Pelo que pedimos na primeira petição?',
    resposta: 'Na primeira petição ("Santificado seja o teu nome") pedimos que Deus nos habilite a nós e aos outros, a glorificá-lo em tudo, pelo que ele se glorifica a si mesmo, e que ele ordenará tudo para a sua própria glória.',
    versiculos: ['Sl 67.1-3', 'Rm 11.36'],
  },
  {
    numero: 102,
    pergunta: 'Pelo que pedimos na segunda petição?',
    resposta: 'Na segunda petição ("Venha o teu reino") pedimos que o reino de Satanás seja destruído, e que o reino da graça seja avançado, a nós mesmos e a outros introduzidos e mantidos nele, e que o reino da glória seja apressado.',
    versiculos: ['Mt 6.10', 'Sl 68.18', '2Ts 3.1', 'Rm 10.1', 'Ap 22.20'],
  },
  {
    numero: 103,
    pergunta: 'Pelo que pedimos na terceira petição?',
    resposta: 'Na terceira petição ("Seja feita a tua vontade assim na terra como no céu") pedimos que Deus, por sua graça, nos torne capazes e dispostos a conhecer, obedecer e submeter-nos à sua vontade em tudo, como os anjos fazem no céu.',
    versiculos: ['Sl 119.36', 'At 21.14', 'Sl 103.20-21'],
  },
  {
    numero: 104,
    pergunta: 'Pelo que pedimos na quarta petição?',
    resposta: 'Na quarta petição ("O pão nosso de cada dia dai-nos hoje") pedimos que, de dádiva gratuita de Deus, recebamos a porção conveniente dos bens deste mundo, e gozemos da sua bênção com eles.',
    versiculos: ['Pv 30.8-9', 'Gn 28.20', 'Mt 6.25-34', '1Tm 4.4-5'],
  },
  {
    numero: 105,
    pergunta: 'Pelo que pedimos na quinta petição?',
    resposta: 'Na quinta petição ("E perdoa-nos as nossas dívidas, assim como nós perdoamos aos nossos devedores") pedimos que Deus, por amor de Cristo, perdoe todos os nossos pecados livremente; o que somos encorajados a pedir porque pela sua graça estamos habilitados do coração a perdoar os outros.',
    versiculos: ['Sl 51.1-9', 'Lc 11.4', 'Mt 18.35'],
  },
  {
    numero: 106,
    pergunta: 'Pelo que pedimos na sexta petição?',
    resposta: 'Na sexta petição ("E não nos deixes cair em tentação, mas livra-nos do mal") pedimos que Deus nos guarde de ser tentados para o pecado, ou que, se somos tentados, nos ampare e liberte.',
    versiculos: ['Mt 26.41', '2Pe 2.9', '1Co 10.13', 'Ef 6.13-17'],
  },
  {
    numero: 107,
    pergunta: 'O que nos ensina o encerramento do Pai Nosso?',
    resposta: 'O encerramento do Pai Nosso ("Porque teu é o reino, o poder e a glória para sempre. Amém.") nos ensina a tirar encorajamento somente de Deus na oração, e a tributar-lhe louvores, assinando-lhe o reino, o poder e a glória; e em testamento da nossa oração e da nossa vontade de ser ouvidos, dizemos "Amém".',
    versiculos: ['Dn 9.4-19', 'Fp 4.6', '1Cr 29.13', '1Co 14.16', 'Ap 22.20'],
  },
]
