// Seed inicial de DoctrineCards — um por tema principal, cobrindo as 4 faixas etárias
// fullText: texto original fiel | summaries: simplificado por faixa (nunca altera doutrina)

import type { DoctrineCard } from './types'

export const DOCTRINE_CARDS: DoctrineCard[] = [
  // ── DEUS ──────────────────────────────────────────────────────────────────
  {
    id: 'cb-1',
    source: 'catecismo-breve',
    reference: 'CB 1',
    question: 1,
    title: 'Para que fui criado?',
    fullText: 'O fim principal do homem é glorificar a Deus e gozar d\'Ele para sempre.',
    summaries: {
      '0-5': 'Você existe para amar a Deus e ser feliz com Ele!',
      '6-8': 'Deus nos criou para que o glorifiquemos e sejamos felizes com Ele para sempre.',
      '9-11': 'O propósito de toda pessoa é glorificar a Deus e desfrutar d\'Ele para sempre.',
      '12-14': 'O fim principal do homem é glorificar a Deus e gozar d\'Ele para sempre.',
    },
    verse: '1Co 10.31',
    verseText: 'Portanto, quer comais, quer bebais ou façais qualquer outra coisa, fazei tudo para a glória de Deus.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['deus', 'gloria'],
    parentTip: 'Pergunte ao seu filho: "Para que você acha que Deus te fez?" Deixe ele responder livremente, depois leia a carta juntos.',
    parentQuestion: 'Quando você agradece a Deus hoje, está glorificando Ele. O que aconteceu hoje que podemos agradecer?',
  },
  {
    id: 'cb-4',
    source: 'catecismo-breve',
    reference: 'CB 4',
    question: 4,
    title: 'O que é Deus?',
    fullText: 'Deus é um Espírito, infinito, eterno e imutável em seu ser, sabedoria, poder, santidade, justiça, bondade e verdade.',
    summaries: {
      '0-5': 'Deus é espírito. Ele está em todo lugar, sempre existiu e nunca muda!',
      '6-8': 'Deus é espírito — não tem corpo. Ele sempre existiu, está em todo lugar e nunca muda.',
      '9-11': 'Deus é espírito, infinito, eterno e imutável. Sua sabedoria, poder, bondade e verdade não têm limite.',
      '12-14': 'Deus é um Espírito, infinito, eterno e imutável em seu ser, sabedoria, poder, santidade, justiça, bondade e verdade.',
    },
    verse: 'Jo 4.24',
    verseText: 'Deus é Espírito, e importa que os seus adoradores o adorem em espírito e em verdade.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['deus'],
    parentTip: 'Use um copo de água para ilustrar: "A água existe mesmo quando não damos forma a ela. Deus é espírito — existe mesmo sem corpo."',
    parentQuestion: 'Se Deus nunca muda, isso é bom ou ruim? Por quê?',
  },
  {
    id: 'cb-5',
    source: 'catecismo-breve',
    reference: 'CB 5',
    question: 5,
    title: 'Há mais de um Deus?',
    fullText: 'Há somente um Deus, vivo e verdadeiro.',
    summaries: {
      '0-5': 'Só existe um Deus!',
      '6-8': 'Existe somente um Deus — vivo e verdadeiro. Os outros "deuses" são invenção.',
      '9-11': 'Há somente um Deus vivo e verdadeiro. Todos os outros são falsos.',
      '12-14': 'Há somente um Deus, vivo e verdadeiro.',
    },
    verse: 'Dt 6.4',
    verseText: 'Ouve, Israel, o Senhor nosso Deus é o único Senhor.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['deus'],
    parentTip: 'Se a criança perguntar sobre outros "deuses" de histórias ou brinquedos, use esta carta para explicar que eles são personagens, não deuses reais.',
    parentQuestion: 'Seu amigo acredita em vários deuses. O que você diria para ele?',
  },

  // ── TRINDADE ──────────────────────────────────────────────────────────────
  {
    id: 'cb-6',
    source: 'catecismo-breve',
    reference: 'CB 6',
    question: 6,
    title: 'A Santíssima Trindade',
    fullText: 'Na Divindade há três pessoas: o Pai, o Filho, e o Espírito Santo; e estas três são um só Deus, da mesma substância, iguais em poder e glória.',
    summaries: {
      '0-5': 'Deus é Pai, Filho e Espírito Santo. Três que são um!',
      '6-8': 'Deus é três pessoas: Pai, Filho e Espírito Santo. São diferentes, mas os três juntos são o único Deus.',
      '9-11': 'Na Divindade há três pessoas — Pai, Filho e Espírito Santo — iguais em poder e glória, que são um só Deus.',
      '12-14': 'Na Divindade há três pessoas: o Pai, o Filho, e o Espírito Santo; e estas três são um só Deus, da mesma substância, iguais em poder e glória.',
    },
    verse: 'Mt 28.19',
    verseText: 'Portanto ide, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 2,
    themes: ['trindade', 'deus'],
    parentTip: 'Não force a analogia do ovo ou do trevo — elas falham. Diga: "É um mistério que Deus revelou, mas não sabemos explicar completamente. E tudo bem!"',
    parentQuestion: 'Jesus rezava para o Pai. O Espírito Santo vive em nós. Como isso mostra que os três são reais?',
  },

  // ── CRIAÇÃO ───────────────────────────────────────────────────────────────
  {
    id: 'cb-9',
    source: 'catecismo-breve',
    reference: 'CB 9',
    question: 9,
    title: 'O que é a criação?',
    fullText: 'A obra da criação é fazer Deus tudo do nada, pelo poder de sua palavra, em seis dias, e tudo muito bom.',
    summaries: {
      '0-5': 'Deus fez tudo — o céu, a terra, os animais e você — só com a sua voz!',
      '6-8': 'Deus criou tudo do nada só pela sua palavra. Antes, não havia nada; depois, havia tudo.',
      '9-11': 'Deus criou o universo do nada pelo poder de sua palavra em seis dias, e declarou tudo muito bom.',
      '12-14': 'A obra da criação é fazer Deus tudo do nada, pelo poder de sua palavra, em seis dias, e tudo muito bom.',
    },
    verse: 'Gn 1.1',
    verseText: 'No princípio, criou Deus os céus e a terra.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['criacao'],
    parentTip: 'Pergunte enquanto olham para fora: "O que você vê que Deus fez?" Liste juntos — árvores, nuvens, pássaros, seu próprio corpo.',
    parentQuestion: 'Se Deus fez tudo e disse que era bom, o que mudou? (Resposta: o pecado entrou no mundo.)',
  },
  {
    id: 'cb-10',
    source: 'catecismo-breve',
    reference: 'CB 10',
    question: 10,
    title: 'Imagem de Deus',
    fullText: 'Deus criou o homem, macho e fêmea, à sua própria imagem, em conhecimento, justiça e santidade, com domínio sobre as criaturas.',
    summaries: {
      '0-5': 'Você foi feito à imagem de Deus! Isso é especial.',
      '6-8': 'Deus criou as pessoas à sua imagem — com capacidade de conhecer o bem, ser justo e santo.',
      '9-11': 'O homem foi criado à imagem de Deus: em conhecimento, justiça e santidade, diferente de todos os animais.',
      '12-14': 'Deus criou o homem, macho e fêmea, à sua própria imagem, em conhecimento, justiça e santidade, com domínio sobre as criaturas.',
    },
    verse: 'Gn 1.27',
    verseText: 'E criou Deus o homem à sua imagem; à imagem de Deus o criou; homem e mulher os criou.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['criacao', 'deus'],
    parentTip: 'Use um espelho: "Quando você olha num espelho, vê a sua imagem. Ser feito à imagem de Deus significa que algo em você reflete quem Ele é."',
    parentQuestion: 'Se fomos feitos à imagem de Deus, como devemos tratar outras pessoas?',
  },

  // ── QUEDA / PECADO ────────────────────────────────────────────────────────
  {
    id: 'cb-14',
    source: 'catecismo-breve',
    reference: 'CB 14',
    question: 14,
    title: 'O que é pecado?',
    fullText: 'O pecado é qualquer falta de conformidade à lei de Deus, ou transgressão da mesma.',
    summaries: {
      '0-5': 'Pecado é quando fazemos o que Deus disse que não é certo.',
      '6-8': 'Pecado é qualquer coisa que vai contra o que Deus manda — seja fazer o errado ou deixar de fazer o certo.',
      '9-11': 'Pecado é não conformar ao que Deus manda, seja por ação, omissão ou atitude do coração.',
      '12-14': 'O pecado é qualquer falta de conformidade à lei de Deus, ou transgressão da mesma.',
    },
    verse: '1Jo 3.4',
    verseText: 'Todo aquele que pratica o pecado também viola a lei, porque o pecado é a violação da lei.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['pecado'],
    parentTip: 'Exemplos concretos ajudam: mentir, desobedecer, ser egoísta. Mas também: deixar de ajudar quando podia, pensar mal do irmão.',
    parentQuestion: 'Você acha que só as coisas que fazemos podem ser pecado, ou os pensamentos também? Por quê?',
  },
  {
    id: 'cb-19',
    source: 'catecismo-breve',
    reference: 'CB 19',
    question: 19,
    title: 'Miséria da queda',
    fullText: 'Toda a humanidade, pela sua queda, perdeu a comunhão com Deus, ficou sob a sua ira e maldição, tornando-se assim sujeita a todas as misérias desta vida, à morte mesma, e às penas do inferno para sempre.',
    summaries: {
      '0-5': 'Quando Adão e Eva pecaram, as pessoas ficaram separadas de Deus. É por isso que o mundo tem tristeza.',
      '6-8': 'Por causa da queda, toda pessoa nasce separada de Deus e sujeita à morte — é por isso que precisamos de um Salvador.',
      '9-11': 'A queda trouxe separação de Deus, morte e sofrimento para toda a humanidade. Só Jesus pode nos restaurar.',
      '12-14': 'Pela queda, a humanidade perdeu a comunhão com Deus, ficou sob ira e maldição, sujeita às misérias desta vida, à morte e às penas eternas.',
    },
    verse: 'Rm 6.23',
    verseText: 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.',
    ageGroups: ['6-8', '9-11', '12-14'],
    difficulty: 2,
    themes: ['queda', 'pecado', 'salvacao'],
  },

  // ── JESUS / SALVAÇÃO ──────────────────────────────────────────────────────
  {
    id: 'cb-21',
    source: 'catecismo-breve',
    reference: 'CB 21',
    question: 21,
    title: 'Quem é o Redentor?',
    fullText: 'O único Redentor dos eleitos de Deus é o Senhor Jesus Cristo, que, sendo o eterno Filho de Deus, fez-se homem, e assim foi, e continua a ser, Deus e homem em duas naturezas distintas, numa só pessoa, para sempre.',
    summaries: {
      '0-5': 'Jesus veio para nos salvar! Ele é Deus e também é homem.',
      '6-8': 'Jesus é o único Salvador. Ele é Deus que se tornou homem para nos resgatar do pecado.',
      '9-11': 'Jesus Cristo é o único Redentor — Deus eterno que se fez homem para salvar os que o Pai lhe deu.',
      '12-14': 'O único Redentor é o Senhor Jesus Cristo: eterno Filho de Deus que se fez homem, sendo Deus e homem em duas naturezas numa só pessoa.',
    },
    verse: '1Tm 2.5',
    verseText: 'Porque há um só Deus e um só Mediador entre Deus e os homens, Cristo Jesus, homem,',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['jesus', 'salvacao'],
    parentTip: 'Natal é um bom momento para usar esta carta: "Por que Jesus nasceu como bebê? Porque precisava ser homem para morrer no nosso lugar."',
    parentQuestion: 'Se Jesus é Deus, por que precisou se tornar homem?',
  },
  {
    id: 'cb-25',
    source: 'catecismo-breve',
    reference: 'CB 25',
    question: 25,
    title: 'Cristo como Sacerdote',
    fullText: 'Cristo exerce o ofício de sacerdote oferecendo-se a si mesmo uma vez como sacrifício para satisfazer a justiça divina e nos reconciliar com Deus, e intercedendo continuamente por nós.',
    summaries: {
      '0-5': 'Jesus morreu no lugar da gente e ainda ora por nós todo dia!',
      '6-8': 'Jesus se ofereceu como sacrifício para pagar pelo nosso pecado e nos perdoar. E ainda ora por nós agora.',
      '9-11': 'Como nosso sacerdote, Jesus se entregou como sacrifício para satisfazer a justiça de Deus e ora continuamente por nós.',
      '12-14': 'Cristo exerceu o ofício de sacerdote oferecendo-se uma vez como sacrifício para satisfazer a justiça divina, e intercede continuamente por nós.',
    },
    verse: 'Hb 7.25',
    verseText: 'Por isso, também pode salvar perfeitamente os que por ele se aproximam de Deus, vivendo sempre para interceder por eles.',
    ageGroups: ['6-8', '9-11', '12-14'],
    difficulty: 2,
    themes: ['jesus', 'salvacao'],
  },

  // ── FÉ / ARREPENDIMENTO ───────────────────────────────────────────────────
  {
    id: 'cb-86',
    source: 'catecismo-breve',
    reference: 'CB 86',
    question: 86,
    title: 'O que é a fé?',
    fullText: 'A fé em Jesus Cristo é uma graça salvadora, pela qual recebemos e descansamos sobre Cristo somente para a salvação, tal como nos é oferecido no Evangelho.',
    summaries: {
      '0-5': 'Fé é confiar em Jesus para nos salvar!',
      '6-8': 'Fé é receber Jesus e descansar nele para ser salvo — não nos nossos esforços, mas nele.',
      '9-11': 'A fé salvadora é confiar em Jesus somente para a salvação, da forma como Ele é oferecido no Evangelho.',
      '12-14': 'A fé em Jesus Cristo é graça salvadora pela qual recebemos e descansamos sobre Cristo somente para a salvação, como nos é oferecido no Evangelho.',
    },
    verse: 'Hb 10.39',
    verseText: 'Mas nós não somos dos que retrocedem para a perdição, mas dos que têm fé para a conservação da alma.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['fe', 'salvacao'],
    parentTip: 'Use a cadeira: "Quando você senta, confia que a cadeira vai segurar você. Fé em Jesus é assim — você se apoia completamente nele."',
    parentQuestion: 'Qual é a diferença entre saber que Jesus existe e ter fé nele?',
  },
  {
    id: 'cb-87',
    source: 'catecismo-breve',
    reference: 'CB 87',
    question: 87,
    title: 'O que é arrependimento?',
    fullText: 'O arrependimento para a vida é uma graça salvadora pela qual um pecador, tendo verdadeiro senso dos seus pecados e apreendendo a misericórdia de Deus em Cristo, com dor e ódio dos seus pecados, se volta deles para Deus, com propósito e esforço de uma nova obediência.',
    summaries: {
      '0-5': 'Arrependimento é sentir que errou, pedir perdão a Deus e querer fazer diferente.',
      '6-8': 'Arrependimento é perceber que pecou, sentir tristeza verdadeira, pedir perdão a Deus e se voltar para Ele.',
      '9-11': 'Arrependimento é reconhecer os pecados com tristeza, confiar na misericórdia de Deus em Cristo, e se voltar dele com desejo de nova obediência.',
      '12-14': 'Arrependimento para a vida é graça salvadora: o pecador, com dor e ódio dos seus pecados, se volta deles para Deus com propósito de nova obediência.',
    },
    verse: 'At 11.18',
    verseText: 'Ouvindo isso, acalmaram-se e glorificaram a Deus, dizendo: Logo, também aos gentios Deus concedeu o arrependimento para a vida.',
    ageGroups: ['6-8', '9-11', '12-14'],
    difficulty: 2,
    themes: ['arrependimento', 'salvacao'],
  },

  // ── ORAÇÃO ────────────────────────────────────────────────────────────────
  {
    id: 'cb-98',
    source: 'catecismo-breve',
    reference: 'CB 98',
    question: 98,
    title: 'O que é a oração?',
    fullText: 'A oração é a oferta das nossas almas a Deus, em nome de Cristo, com confissão dos nossos pecados e reconhecimento grato das suas misericórdias.',
    summaries: {
      '0-5': 'Oração é falar com Deus! Ele nos ouve.',
      '6-8': 'Oração é conversar com Deus — agradecer, confessar erros e pedir, tudo em nome de Jesus.',
      '9-11': 'Orar é oferecer nossa alma a Deus em nome de Cristo, confessando pecados e reconhecendo sua bondade.',
      '12-14': 'A oração é a oferta das nossas almas a Deus em nome de Cristo, com confissão dos pecados e reconhecimento grato das suas misericórdias.',
    },
    verse: 'Fp 4.6',
    verseText: 'Não andeis ansiosos por coisa alguma; antes as vossas petições sejam conhecidas em toda oração e súplica diante de Deus, e a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos pensamentos em Cristo Jesus.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['oracao'],
    parentTip: 'Ore junto com a criança usando este cartão. Mostre que é natural, não cerimonioso. Até 2 frases já são uma oração real.',
    parentQuestion: 'Por que precisamos orar em nome de Jesus e não direto para Deus com o nosso próprio nome?',
  },

  // ── LEI / MANDAMENTOS ─────────────────────────────────────────────────────
  {
    id: 'cb-42',
    source: 'catecismo-breve',
    reference: 'CB 42',
    question: 42,
    title: 'Resumo da lei',
    fullText: 'A suma dos dez mandamentos é amar ao Senhor nosso Deus com todo o coração, com toda a alma, com todas as forças e com todo o entendimento, e ao nosso próximo como a nós mesmos.',
    summaries: {
      '0-5': 'Ame a Deus com tudo! E ame as pessoas como você ama você mesmo.',
      '6-8': 'Toda a lei de Deus se resume em duas coisas: amar a Deus com tudo, e amar o próximo como a si mesmo.',
      '9-11': 'A lei de Deus se resume em amar a Deus de todo o coração e amar o próximo como a si mesmo — os dez mandamentos explicam isso.',
      '12-14': 'A suma dos dez mandamentos é amar ao Senhor nosso Deus com todo o coração, alma, forças e entendimento, e ao nosso próximo como a nós mesmos.',
    },
    verse: 'Mt 22.37-39',
    verseText: 'Amarás o Senhor teu Deus de todo o teu coração, de toda a tua alma e de todo o teu entendimento. Este é o grande e primeiro mandamento. O segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['lei', 'mandamentos'],
    parentTip: 'Quando houver briga entre irmãos, esta é a carta certa. "A lei de Deus diz para amar o próximo como você mesmo. Seu irmão é seu próximo."',
    parentQuestion: 'Se você ama alguém de verdade, o que você naturalmente quer fazer por essa pessoa?',
  },

  // ── JUSTIFICAÇÃO ─────────────────────────────────────────────────────────
  {
    id: 'cb-33',
    source: 'catecismo-breve',
    reference: 'CB 33',
    question: 33,
    title: 'O que é justificação?',
    fullText: 'A justificação é um ato de livre graça de Deus pelo qual ele perdoa todos os nossos pecados, e nos aceita como justos perante ele, somente imputando-nos a justiça de Cristo, e recebendo-a somente pela fé.',
    summaries: {
      '0-5': 'Deus nos perdoa e nos trata como se nunca tivéssemos pecado, por causa de Jesus!',
      '6-8': 'Justificação é Deus nos perdoar e nos aceitar como justos por causa de Jesus — não porque somos bons.',
      '9-11': 'Deus justifica o pecador de graça: perdoa todos os pecados e imputa a justiça de Cristo, recebida pela fé.',
      '12-14': 'A justificação é ato de livre graça: Deus perdoa todos os nossos pecados e nos aceita como justos somente pela justiça de Cristo, recebida pela fé.',
    },
    verse: 'Rm 3.24',
    verseText: 'sendo justificados gratuitamente por sua graça, pela redenção que está em Cristo Jesus.',
    ageGroups: ['6-8', '9-11', '12-14'],
    difficulty: 2,
    themes: ['justificacao', 'salvacao', 'jesus'],
  },
  {
    id: 'cb-36',
    source: 'catecismo-breve',
    reference: 'CB 36',
    question: 36,
    title: 'Benefícios da salvação',
    fullText: 'Os benefícios que nesta vida acompanham ou procedem da justificação, adoção e santificação são: segurança do amor de Deus, paz de consciência, alegria no Espírito Santo, aumento da graça e perseverança nela até ao fim.',
    summaries: {
      '0-5': 'Quando Deus nos salva, nos dá paz, alegria e cuida de nós até o fim!',
      '6-8': 'Quem é salvo recebe paz de coração, alegria no Espírito e a certeza de que Deus vai cuidar até o fim.',
      '9-11': 'A salvação traz segurança do amor de Deus, paz, alegria no Espírito e perseverança até o fim.',
      '12-14': 'Os benefícios da salvação nesta vida: segurança do amor de Deus, paz de consciência, alegria no Espírito Santo e perseverança até ao fim.',
    },
    verse: 'Rm 5.1',
    verseText: 'Tendo, pois, sido justificados por fé, temos paz para com Deus, por meio de nosso Senhor Jesus Cristo.',
    ageGroups: ['9-11', '12-14'],
    difficulty: 2,
    themes: ['salvacao', 'santificacao', 'fe'],
  },
  {
    id: 'cb-82',
    source: 'catecismo-breve',
    reference: 'CB 82',
    question: 82,
    title: 'Ninguém é perfeito',
    fullText: 'Nenhum homem, desde a queda, é capaz nesta vida de guardar perfeitamente os mandamentos de Deus; mas os transgride em pensamentos, palavras e atos diariamente.',
    summaries: {
      '0-5': 'Ninguém consegue obedecer a Deus perfeitamente. É por isso que precisamos de Jesus!',
      '6-8': 'Desde a queda, nenhuma pessoa consegue obedecer perfeitamente a Deus. Todos pecam em pensamentos, palavras e ações.',
      '9-11': 'Nenhum ser humano desde a queda consegue guardar a lei de Deus perfeitamente. Todos transgridem diariamente.',
      '12-14': 'Nenhum homem, desde a queda, guarda perfeitamente os mandamentos: os transgride em pensamentos, palavras e atos diariamente.',
    },
    verse: 'Ec 7.20',
    verseText: 'Deveras não há homem justo na terra que faça o bem e nunca peque.',
    ageGroups: ['9-11', '12-14'],
    difficulty: 2,
    themes: ['pecado', 'lei'],
  },
  {
    id: 'cb-39',
    source: 'catecismo-breve',
    reference: 'CB 39',
    question: 39,
    title: 'Dever do homem',
    fullText: 'O dever que Deus requer do homem é a obediência à sua vontade revelada.',
    summaries: {
      '0-5': 'Deus quer que obedeçamos a ele!',
      '6-8': 'Deus quer que façamos o que ele revelou na Bíblia — isso é nosso dever.',
      '9-11': 'O que Deus pede de nós é obediência à sua vontade tal como está revelada na Escritura.',
      '12-14': 'O dever que Deus requer do homem é a obediência à sua vontade revelada.',
    },
    verse: 'Mq 6.8',
    verseText: 'Ele te declarou, ó homem, o que é bom; e que é o que o Senhor pede de ti, senão que pratiques a justiça, e ames a misericórdia, e andes humildemente com o teu Deus?',
    ageGroups: ['9-11', '12-14'],
    difficulty: 1,
    themes: ['lei', 'obediencia'],
  },
  {
    id: 'cb-40',
    source: 'catecismo-breve',
    reference: 'CB 40',
    question: 40,
    title: 'A lei moral',
    fullText: 'A regra que Deus revelou primeiro ao homem para a obediência foi a lei moral.',
    summaries: {
      '0-5': 'Deus nos deu regras para sabermos o que é certo!',
      '6-8': 'Deus revelou a lei moral para mostrar o que ele espera de nós.',
      '9-11': 'A primeira regra de obediência que Deus revelou foi a lei moral — resumida nos dez mandamentos.',
      '12-14': 'A regra que Deus revelou primeiro ao homem para a obediência foi a lei moral.',
    },
    verse: 'Rm 10.5',
    verseText: 'Porque Moisés escreve a respeito da justiça que procede da lei: O homem que praticar estas coisas viverá por elas.',
    ageGroups: ['9-11', '12-14'],
    difficulty: 2,
    themes: ['lei', 'mandamentos'],
  },

  // ── CFW: ESCRITURA ────────────────────────────────────────────────────────
  {
    id: 'cfw-1-7',
    source: 'cfw',
    reference: 'CFW 1.7',
    chapter: 1,
    paragraph: 7,
    title: 'A Bíblia é clara',
    fullText: 'As coisas necessárias para a salvação são tão claramente expostas em algum lugar da Escritura, que tanto o erudito quanto o leigo podem alcançar entendimento suficiente delas.',
    summaries: {
      '0-5': 'A Bíblia fala claro! Qualquer pessoa pode entender o que precisa para ser salva.',
      '6-8': 'A Bíblia é tão clara que qualquer pessoa — seja criança ou adulto, sábio ou simples — pode entender o que precisa para ser salva.',
      '9-11': 'As verdades necessárias para a salvação estão claramente na Escritura. Qualquer pessoa pode entendê-las com o Espírito Santo.',
      '12-14': 'As coisas necessárias para a salvação são tão claramente expostas na Escritura que tanto o erudito quanto o leigo podem alcançar entendimento suficiente.',
    },
    verse: 'Sl 119.105',
    verseText: 'Lâmpada para os meus pés é a tua palavra e luz para os meus caminhos.',
    ageGroups: ['6-8', '9-11', '12-14'],
    difficulty: 2,
    themes: ['escritura'],
  },

  // ── CFW: PROVIDÊNCIA ──────────────────────────────────────────────────────
  {
    id: 'cfw-5-1',
    source: 'cfw',
    reference: 'CFW 5.1',
    chapter: 5,
    paragraph: 1,
    title: 'Deus governa tudo',
    fullText: 'Deus, o grande Criador de tudo, sustenta, dirige, dispõe e governa todas as criaturas, ações e coisas, desde a maior até a menor, pela sua sábia e santa providência.',
    summaries: {
      '0-5': 'Deus cuida de tudo — até dos passarinhos! Ele também cuida de você.',
      '6-8': 'Deus governa tudo que existe — cada animal, cada pessoa, cada coisa que acontece — com sabedoria.',
      '9-11': 'Deus sustenta e governa todas as criaturas e eventos, desde os maiores até os menores, pela sua providência sábia e santa.',
      '12-14': 'Deus sustenta, dirige e governa todas as criaturas, ações e coisas, desde a maior até a menor, pela sua sábia e santa providência.',
    },
    verse: 'Mt 10.29',
    verseText: 'Não se vendem dois pardais por um asse? E nenhum deles cairá em terra sem o consentimento de vosso Pai.',
    ageGroups: ['0-5', '6-8', '9-11', '12-14'],
    difficulty: 1,
    themes: ['providencia', 'deus'],
    parentTip: 'Na próxima vez que a criança tiver medo, use esta carta: "Deus governa até o que assusta. Nada acontece sem que Ele saiba."',
    parentQuestion: 'Se Deus governa tudo, por que ainda há coisas ruins no mundo?',
  },

  // ── CFW: FAMÍLIA ──────────────────────────────────────────────────────────
  {
    id: 'cfw-24-1',
    source: 'cfw',
    reference: 'CFW 24.1',
    chapter: 24,
    paragraph: 1,
    title: 'O casamento',
    fullText: 'O matrimônio deve ser entre um homem e uma mulher. Não é lícito ao homem ter mais de uma esposa, nem à mulher mais de um marido.',
    summaries: {
      '0-5': 'Deus criou a família: um pai e uma mãe para cuidar dos filhos.',
      '6-8': 'Deus criou o casamento entre um homem e uma mulher para se ajudarem e formarem família.',
      '9-11': 'O casamento foi instituído por Deus entre um homem e uma mulher para auxílio mútuo e para ter filhos que o conheçam.',
      '12-14': 'O matrimônio deve ser entre um homem e uma mulher, instituído por Deus para auxílio mútuo e para que filhos sejam criados no conhecimento do Senhor.',
    },
    verse: 'Gn 2.24',
    verseText: 'Por isso, deixará o homem pai e mãe e se unirá à sua mulher, tornando-se os dois uma só carne.',
    ageGroups: ['6-8', '9-11', '12-14'],
    difficulty: 2,
    themes: ['familia'],
  },
]
