// Seed inicial de SituationCards — cenários reais do cotidiano por faixa etária
// acceptedDoctrineIds: IDs de DoctrineCards que respondem corretamente a situação

import type { SituationCard } from './types'

export const SITUATION_CARDS: SituationCard[] = [
  // ── FAIXA 0-5 (modo pai) ──────────────────────────────────────────────────
  {
    id: 'sit-05-001',
    scenario: 'Seu filho pergunta: "Pai, quem fez o céu e as estrelas?"',
    question: 'Qual carta você usa para responder?',
    ageGroup: '0-5',
    difficulty: 1,
    themes: ['criacao', 'deus'],
    acceptedDoctrineIds: ['cb-9', 'cfw-5-1'],
    parentNarration: 'Filho, quem você acha que fez o céu cheio de estrelas?',
    hint: 'Deus criou tudo!',
  },
  {
    id: 'sit-05-002',
    scenario: 'A criança bate no irmão e você pergunta: "Por que isso é errado?"',
    question: 'Qual carta você usa para explicar?',
    ageGroup: '0-5',
    difficulty: 1,
    themes: ['pecado', 'mandamentos'],
    acceptedDoctrineIds: ['cb-14', 'cb-42'],
    parentNarration: 'Quando você bate no irmão, está fazendo o que Deus gosta ou o que Ele disse que é errado?',
    hint: 'Pecado é quando fazemos o que Deus disse que não é certo.',
  },
  {
    id: 'sit-05-003',
    scenario: 'Seu filho está com medo do escuro e chora antes de dormir.',
    question: 'Qual carta conforta e ensina ao mesmo tempo?',
    ageGroup: '0-5',
    difficulty: 1,
    themes: ['providencia'],
    acceptedDoctrineIds: ['cfw-5-1', 'cb-98'],
    parentNarration: 'Você sabia que Deus está aqui mesmo quando está escuro? Vamos falar com Ele?',
    hint: 'Deus cuida de tudo — até do escuro!',
  },

  // ── FAIXA 6-8 ─────────────────────────────────────────────────────────────
  {
    id: 'sit-68-001',
    scenario: 'Seu amigo diz: "Eu acredito em vários deuses — o do trovão, o do mar..."',
    question: 'Qual verdade você usaria para responder?',
    ageGroup: '6-8',
    difficulty: 1,
    themes: ['deus'],
    acceptedDoctrineIds: ['cb-5', 'cb-4'],
    hint: 'Há somente um Deus!',
  },
  {
    id: 'sit-68-002',
    scenario: 'Na escola, a professora diz que os humanos são apenas animais evoluídos, sem nada de especial.',
    question: 'O que a Bíblia diz sobre o valor das pessoas?',
    ageGroup: '6-8',
    difficulty: 2,
    themes: ['criacao'],
    acceptedDoctrineIds: ['cb-10', 'cb-9'],
    hint: 'Você foi feito à imagem de Deus.',
  },
  {
    id: 'sit-68-003',
    scenario: 'Você mente para sua mãe para não se meter em problema. Depois sente aquela coisa estranha no peito.',
    question: 'O que é essa sensação e o que você deveria fazer?',
    ageGroup: '6-8',
    difficulty: 1,
    themes: ['pecado', 'arrependimento'],
    acceptedDoctrineIds: ['cb-14', 'cb-87'],
    hint: 'Mentira é pecado. E Deus dá o dom do arrependimento.',
  },
  {
    id: 'sit-68-004',
    scenario: 'Seu colega pergunta: "Por que você reza antes de comer? Deus nem existe!"',
    question: 'Como você explica por que ora?',
    ageGroup: '6-8',
    difficulty: 2,
    themes: ['oracao', 'deus'],
    acceptedDoctrineIds: ['cb-98', 'cb-4', 'cb-5'],
  },
  {
    id: 'sit-68-005',
    scenario: 'Você está de mal humor e trata seu irmão com grosseria sem motivo.',
    question: 'O que Deus pede de você nessa situação?',
    ageGroup: '6-8',
    difficulty: 1,
    themes: ['mandamentos', 'arrependimento'],
    acceptedDoctrineIds: ['cb-42', 'cb-87'],
    hint: 'Ame o próximo como a si mesmo.',
  },

  // ── FAIXA 9-11 ────────────────────────────────────────────────────────────
  {
    id: 'sit-911-001',
    scenario: 'Um amigo diz: "Jesus foi só um bom professor, igual a Buda ou Maomé."',
    question: 'O que torna Jesus diferente de todos os outros?',
    ageGroup: '9-11',
    difficulty: 2,
    themes: ['jesus', 'salvacao'],
    acceptedDoctrineIds: ['cb-21', 'cb-25'],
    hint: 'Jesus é o único Redentor.',
  },
  {
    id: 'sit-911-002',
    scenario: 'Você vê um acidente grave na notícia e pensa: "Se Deus existe, por que deixou isso acontecer?"',
    question: 'Como a doutrina da providência ajuda a entender momentos assim?',
    ageGroup: '9-11',
    difficulty: 3,
    themes: ['providencia', 'deus'],
    acceptedDoctrineIds: ['cfw-5-1', 'cb-4'],
  },
  {
    id: 'sit-911-003',
    scenario: 'Seu primo diz: "Eu sou uma boa pessoa, então Deus vai me aceitar no céu."',
    question: 'O que a Bíblia diz sobre como somos salvos?',
    ageGroup: '9-11',
    difficulty: 2,
    themes: ['salvacao', 'fe', 'pecado'],
    acceptedDoctrineIds: ['cb-86', 'cb-82', 'cb-33'],
    hint: 'Ninguém é bom o suficiente — salvação é pela fé em Cristo.',
  },
  {
    id: 'sit-911-004',
    scenario: 'Você sente culpa por um pecado que já confessou várias vezes e pensa que Deus não perdoou de verdade.',
    question: 'O que a Escritura diz sobre o perdão de Deus?',
    ageGroup: '9-11',
    difficulty: 2,
    themes: ['salvacao', 'fe', 'arrependimento'],
    acceptedDoctrineIds: ['cb-33', 'cb-87', 'cb-86'],
  },
  {
    id: 'sit-911-005',
    scenario: 'Seu amigo ateu diz: "A Bíblia foi escrita por humanos. Como você sabe que é verdade?"',
    question: 'O que a Confissão ensina sobre a autoridade da Bíblia?',
    ageGroup: '9-11',
    difficulty: 3,
    themes: ['escritura'],
    acceptedDoctrineIds: ['cfw-1-7'],
  },

  // ── FAIXA 12-14 ───────────────────────────────────────────────────────────
  {
    id: 'sit-1214-001',
    scenario: 'Na aula de filosofia, o professor diz que o propósito da vida é cada um escolher o seu próprio.',
    question: 'O que a CFW diz sobre o propósito do homem?',
    ageGroup: '12-14',
    difficulty: 2,
    themes: ['deus', 'gloria'],
    acceptedDoctrineIds: ['cb-1'],
  },
  {
    id: 'sit-1214-002',
    scenario: 'Um colega diz: "Se Deus predestinou tudo, por que minhas escolhas importam? Tanto faz o que eu fizer."',
    question: 'Como a doutrina do decreto eterno e do livre-arbítrio se relacionam?',
    ageGroup: '12-14',
    difficulty: 3,
    themes: ['deus', 'pecado'],
    acceptedDoctrineIds: ['cfw-5-1'],
  },
  {
    id: 'sit-1214-003',
    scenario: 'Você pensa: "Será que sou realmente salvo? Às vezes ainda peco muito."',
    question: 'O que a Escritura ensina sobre a certeza da salvação e perseverança?',
    ageGroup: '12-14',
    difficulty: 3,
    themes: ['salvacao', 'fe', 'santificacao'],
    acceptedDoctrineIds: ['cb-86', 'cb-87', 'cb-36'],
  },
  {
    id: 'sit-1214-004',
    scenario: 'Sua namorada diz que a Trindade não faz sentido: "Ou é um Deus ou são três — escolha."',
    question: 'Como você explica a doutrina da Trindade?',
    ageGroup: '12-14',
    difficulty: 3,
    themes: ['trindade', 'deus'],
    acceptedDoctrineIds: ['cb-6'],
  },
  {
    id: 'sit-1214-005',
    scenario: 'Um amigo diz que a lei de Deus foi abolida — que no Novo Testamento não existem mais regras.',
    question: 'Qual é o papel da lei moral para o cristão?',
    ageGroup: '12-14',
    difficulty: 3,
    themes: ['lei', 'mandamentos', 'santificacao'],
    acceptedDoctrineIds: ['cb-42', 'cb-39', 'cb-40'],
  },
]
